### ISSUE TITLE
How to we search for an anime?

### ISSUE THREAD

**Issue by dheerajbred** [neckaros/anilist#1]
How to we search for an anime?

**Comment by neckaros** [comment]
```dart
test('request media query', () async {
    final request = AnilistMediaRequest();
    request
      ..withIdMal()
      ..withTitle();
    request.querySearch('attack');
    var result = await request.list(10, 1);
    expect(result.results, hasLength(10));
    expect(
        result.results.first.title.english.toLowerCase(), contains('attack'));
    print(result);
  });
```

I have made a lot of examples in the test file hope it can help you!
https://github.com/neckaros/anilist/blob/master/test/anilist_media_request_test.dart

Tell me if you need more options I can add them. (I only coded for now what I needed in my own app)

**Comment by neckaros** [comment]
And you can add a
```dart 
..queryType(AnilistMediaType.ANIME);
```

To only get anime

**Comment by dheerajbred** [comment]
Thanks a lot for your help.

I am not able to fetch the trailer. It always shows null for me.
For example https://anilist.co/anime/101921/Kaguyasama-wa-Kokurasetai-Tensaitachi-no-Renai-Zunousen/

![image](https://user-images.githubusercontent.com/46578244/83274990-2860ae80-a1ec-11ea-93b9-b74f05df0aec.png)

![image](https://user-images.githubusercontent.com/46578244/83275131-6067f180-a1ec-11ea-921f-48261e5ba3c8.png)


Am I missing something?

**Comment by neckaros** [comment]
Please open another issue and I will look into it asap!
