### ISSUE TITLE
Not able to fetch the trailer

### ISSUE THREAD

**Issue by dheerajbred** [neckaros/anilist#2]
I am not able to fetch the trailer. It always shows null for me.
For example https://anilist.co/anime/101921/Kaguyasama-wa-Kokurasetai-Tensaitachi-no-Renai-Zunousen/

![image](https://user-images.githubusercontent.com/46578244/83282264-f3a62480-a1f6-11ea-95fe-0d6b9f374b2d.png)

![image](https://user-images.githubusercontent.com/46578244/83282249-ef7a0700-a1f6-11ea-9c85-d22ae7aaad10.png)

Am I missing something?

**Comment by dheerajbred** [comment]
I forgot to add ..withTrailer() to the request. This is working fine. 
Thank you for this plugin.

Please do share a link to your complete app if you are okay with it. I would love to check it out.

Cheers!

**Comment by neckaros** [comment]
Very glad it could help you! I will but not ready for prime time yet ;)
And please share yours when ready!
